substitutions:
  devicename: esp-drzwi
  friendly_name: esp-drzwi

esphome:
  name: $devicename

esp32:
  board: esp32cam
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0
  #level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota

wifi:
  ssid: !secret iot_ssid
  password: !secret iot_password
  manual_ip:
    static_ip: 10.10.10.120
    gateway: 10.10.10.1
    subnet: 255.255.255.0
  ap:
    ssid: 1Fallback Hotspot
    password: !secret lampka_fallback_password

captive_portal:

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: Dzwi
  icon: mdi:camera
  idle_framerate: 0.2 fps # default: 0.1 fps - framerate for 'picture' in HA dashboard
  max_framerate: 10 fps
  resolution: 1600X1200
  
  jpeg_quality: 10
  brightness: 0 # default: 0, variable -2 to 2
  contrast: 0 # default: 0, variable -2 to 2
  saturation: 0 # default: 0, variable -2 to 2
  special_effect: none
  
  #Exposure
  aec_mode: auto
  ae_level: 0

  #Gain
  agc_mode: auto
  agc_gain_ceiling: 2x

  wb_mode: auto
  vertical_flip: true
  horizontal_mirror: true

#Stream
esp32_camera_web_server:
  - port: 80
    mode: stream
  - port: 81
    mode: snapshot

external_components:
  - source: components
    components: [ ja63k ]
  # - source:
  #     type: git
  #     url: https://github.com/oxan/esphome-stream-server.git
  #     ref: master
  #   components: [ stream_server ]

ja63k:

sensor:
  - platform: ja63k
    mode:
      name: Mode
      filters:
        delta: 1
    power:
      name: Power
      filters:
        delta: 1
    alarm:
      name: Alarm
      filters:
        delta: 1
    tamper:
      name: Tamper
      filters:
        delta: 1
    malfunction:
      name: Malfunction
      filters:
        delta: 1
    lock:
      name: Lock
      filters:
        delta: 1
    wireless:
      name: Wireless
      filters:
        delta: 1
    beep:
      name: beep
      filters:
        delta: 1
  - platform: wifi_signal
    name: $friendly_name Wifi signal
    update_interval: 10s
  - platform: uptime
    name: $friendly_name Uptime

text_sensor:
  - platform: ja63k
    status:
      name: 'text'
    display:
      name: display
  - platform: version
    name: $friendly_name ESPHome Version
  - platform: wifi_info
    ssid:
      name: $friendly_name WiFi

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  # debug:
  #   direction: BOTH
  #   dummy_receiver: true
  #   sequence:
  #     - lambda: UARTDebug::log_string(direction, bytes);

button:
  - platform: restart
    name: Restart
  - platform: ja63k
    Key_1:
      name: "1"
    Key_2:
      name: "2"
    Key_3:
      name: "3"
    Key_4:
      name: "4"
    Key_5:
      name: "5"
    Key_6:
      name: "6"
    Key_7:
      name: "7"
    Key_8:
      name: "8"
    Key_9:
      name: "9"
    Key_F:
      name: "F"
    Key_0:
      name: "0"
    Key_N:
      name: "N"
